# Generated by Django 3.1.3 on 2021-06-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
